###############################################

# Run GitHub's Super Linter against code base #

###############################################



name: GitHub's Super Linter

on: push



jobs:

  run-linters:

    name: GitHub's Super Linter

    runs-on: ubuntu-latest



    steps:

      - name: Check out Git repository

        uses: actions/checkout@master

        

      - name: Run GitHub Super Linter

        uses: github/super-linter@main

        env:

          VALIDATE_ALL_CODEBASE: true

          VALIDATE_JAVASCRIPT_STANDARD: false

          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



Then place the following code in a README.md file in your root folder (this you can do in Repl.it):

Make sure you replace <OWNER> with your Github Account name, and <REPOSITORY> with the name of your project!

[![GitHub's Super Linter](https://github.com/<OWNER>/<REPOSITORY>/workflows/GitHub's%20Super%20Linter/badge.svg)](https://github.com/<OWNER>/<REPOSITORY>/actions)



This website can be found at: [https://<OWNER>.github.io/<REPOSITORY>](https://<OWNER>.github.io/<REPOSITORY>)
